sudo: required
services:
  - docker

before_install:
  - docker build -t mohammeds96/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true mohammeds96/react-test npm test

after_success:
  - docker build -t mohammeds96/m-client ./client
  - docker build -t mohammeds96/m-nginx ./nginx
  - docker build -t mohammeds96/m-server ./server
  - docker build -t mohammeds96/m-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mohammeds96/m-client
  - docker push mohammeds96/m-nginx
  - docker push mohammeds96/m-server
  - docker push mohammeds96/m-worker